### ISSUE TITLE
Update to latest Proxmox Kernel

### ISSUE THREAD

**Issue by djarbz** [Aterfax/relax-intel-rmrr#19] opened 2022-09-30 12:20 UTC
I'm just requesting that you push an update for the latest Proxmox Kernel version.

Thank you.

**Comment by accessiblepixel** [comment] 2022-09-30 20:34
It looks like the autobuild script is failing, usually @Aterfax has the kernel be built every Saturday from the sources, and something in the patch process is failing.

**Comment by Aterfax** [comment] 2022-09-30 20:37
Correct, something within the upstream patches is not patching correctly stopping the build from continuing and I've not had the time to investigate what is going wrong upstream.

It may be that I need to swap it to build from a different PVE_KERNEL_BRANCH within - https://github.com/Aterfax/relax-intel-rmrr/blob/master/build/proxmox/build_latest.sh

**Comment by Aterfax** [comment] 2022-09-30 22:13
Looks like the root of the issue is the change here: https://git.proxmox.com/?p=pve-kernel.git;a=blobdiff;f=debian/scripts/find-firmware.pl;h=17cdaf817e64368e79a706e8e904a407f87a5ba4;hp=4d72d4e80f213249d7c9bdc0d510b7c44c9cbb63;hb=35fd42877fcc7c4d3ecb4c9199cb526573b64522;hpb=81dd1548115564e25eee8d0df1466231399280f8

The adjustment means the existing patch file is no longer valid. As the line to be patched has gone I will remove this section of the patch out as it is no longer needed.

See:

https://github.com/Aterfax/relax-intel-rmrr/blob/master/patches/proxmox7.patch
https://github.com/Aterfax/relax-intel-rmrr/blob/master/patches/proxmox.patch

**Comment by Aterfax** [comment] 2022-09-30 22:50
This was resolved by https://github.com/Aterfax/relax-intel-rmrr/pull/20
Tested on my local development machine which finished making a kernel.

CI/CD build now running in https://github.com/Aterfax/relax-intel-rmrr/actions/runs/3162013761/jobs/5148279198 for which you can get the files once it finishes.

I will likely test what it makes on my Proxmox machine this weekend and push a proper release shortly.

**Closed by Aterfax** 2022-09-30 22:50 UTC

**Comment by Aterfax** [comment] 2022-10-01 00:29
The latest build artifact can now be found here: https://github.com/Aterfax/relax-intel-rmrr/actions/runs/3162013761

**Comment by accessiblepixel** [comment] 2022-10-01 11:59
> The latest build artifact can now be found here: https://github.com/Aterfax/relax-intel-rmrr/actions/runs/3162013761

@Aterfax You're a star, mate. Just tested the build from that action and it works perfectly fine on my G6 DL360 passing through a NIC. Haven't tested on my G8, but I tend not to update that machine that often (It's our storage!).

`Linux ritsuko 5.19.7-1-pve-relaxablermrr #1 SMP PREEMPT_DYNAMIC PVE 5.19.7-1 (Tue, 06 Sep 2022 07:54:58 + x86_64 GNU/Linux`

❤️ 
P.S: I finally got my 'test bed' machine up and running so I don't end up nuking an important machine if something goes wrong testing, so hopefully now when there's a build I can test them a bit quicker for ya :) Thanks again!

~ Jessica
